[project]
name = "nooda"
version = "0.1.0"
description = ""
authors = [{ name = "Tom Booth", email = "tom.booth@rvu.co.uk" }]
requires-python = ">=3.12"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "beautifulsoup4>=4.14.3",
    "marko>=2.2.2",
    "matplotlib>=3.10.8",
    "nbformat>=5.10.4",
    "pandas>=2.3.3",
    "slack-sdk>=3.39.0",
    "tabulate>=0.9.0",
]

[dependency-groups]
dev = [
    "db-dtypes>=1.5.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "nbconvert>=7.16.6",
    "pyarrow>=23.0.0",
    "pytest>=9.0.2",
]

[tool.uv]

[tool.uv.build-backend]
module-name = ["nooda"]
module-root = ""

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
